image:
  repository: ghcr.io/dericko681/lightbridge-authz1
  pullPolicy: Always
  tag: "latest"

replicaCount: 1

service:
  type: ClusterIP
  ports:
    - name: rest
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: grpc
      port: 3001
      targetPort: 3001
      protocol: TCP

env:
  - name: RUST_LOG
    value: "info"
  - name: CONFIG_PATH
    value: "/app/config/config.yaml"

# Add config volume
volumes:
  - name: config
    configMap:
      name: lightbridge-authz-config

volumeMounts:
  - name: config
    mountPath: /app/config
    readOnly: true

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

livenessProbe:
  tcpSocket:
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  tcpSocket:
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 5
