{{- range $name, $p := .Values.providers }}
{{ with $p }}
{{ if and .enabled .auth .auth.enabled }}
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: BackendSecurityPolicy
metadata:
  name: {{ $name }}
  namespace: {{ include "common.names.namespace" $ }}
spec:
  targetRefs:
    - group: aigateway.envoyproxy.io
      kind: AIServiceBackend
      name: {{ $name }}

  {{ with .auth }}
  {{ if eq $p.type "openai" }}
  type: APIKey
  apiKey:
    secretRef:
      name: {{ include "common.tplvalues.render" ( dict "value" .secret_name "context" $ ) }}
      namespace: {{ include "common.names.namespace" $ }}
  {{ else if eq $p.type "aws" }}
  type: AWSCredentials
  awsCredentials:
    region: {{ include "common.tplvalues.render" ( dict "value" .region "context" $ ) }}
    credentialsFile:
      secretRef:
        name: {{ include "common.tplvalues.render" ( dict "value" .secret_name "context" $ ) }}
  {{ else if eq $p.type "google" }}
  type: GCPCredentials
  gcpCredentials:
    projectName: {{ include "common.tplvalues.render" ( dict "value" .projectName "context" $ ) }}
    region: {{ include "common.tplvalues.render" ( dict "value" .region "context" $ ) }}
    credentialsFile:
      secretRef:
        name: {{ include "common.tplvalues.render" ( dict "value" .secret_name "context" $ ) }}
  {{ else }}
  {{ fail "type not supported yet" }}
  {{ end }}
  {{ end }}
---
{{ end -}}
{{ end -}}
{{ end -}}
