{{ with .Values.clientTraffic }}
{{ if .enabled }}
# By default, Envoy Gateway sets the buffer limit to 32kiB which is not sufficient for AI workloads.
# This ClientTrafficPolicy sets the buffer limit to 50MiB as an example.
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: client-buffer-limit
  namespace: default
spec:
  targetRefs:
    - {{ include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 6 }}

  {{ with .enableProxyProtocol }}
  enableProxyProtocol:
    {{ include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{ end }}

  {{ with .tcpKeepalive }}
  tcpKeepalive:
    {{ include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{ end }}

  {{ with .connection }}
  connection:
    {{ include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{ end }}
{{ end }}
{{ end }}
