apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ include "common.names.fullname" $ }}-rl-requests
  namespace: {{ include "common.names.namespace" $ }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ include "common.names.fullname" $ }}
  rateLimit:
    type: Global
    global:
      rules:
      {{- range $tierName, $_ := .Values.tiers }}
        {{- range $i, $model := $.Values.models }}
          {{- if eq (include "allowed" (dict "tier" $tierName "model" $model.name "context" $) ) "true" }}
        - clientSelectors:
            - headers: [ { name: {{ include "H.user" $ }}, type: Distinct } ]
            - headers: [ { name: {{ include "H.tier" $ }}, value: {{ $tierName }} } ]
            - headers: [ { name: {{ include "H.model" $ }}, value: {{ $model.name }} } ]
          limit:
            requests: {{ include "limit.get" (dict "tier" $tierName "kind" "reqPerMin" "model" $model.name "context" $) | int }}
            unit: Minute
          {{- end }}
        {{- end }}
      {{- end }}
