[workspace]
members = [
    "crates/lightbridge-authz-proto",
    "crates/lightbridge-authz-core",
    "crates/lightbridge-authz-grpc",
]
resolver = "3"

[workspace.dependencies]
lightbridge-authz-core = { path = "./crates/lightbridge-authz-core" }
lightbridge-authz-proto = { path = "./crates/lightbridge-authz-proto" }
lightbridge-authz-grpc = { path = "./crates/lightbridge-authz-grpc" }

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic = "0.12"
tonic-build = "0.12"
prost = "0.13"
prost-types = "0.13"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
axum = "0.7"