---

services:
  postgresql:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      POSTGRESQL_DATABASE: 'lightbridge_authz'

  adminer:
    image: adminer
    ports:
      - "18080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_USERNAME: ${POSTGRES_USER:-postgres}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-postgres-password}
      ADMINER_DESIGN: ${ADMINER_DESIGN:-dracula}
      ADMINER_PLUGINS: ${ADMINER_PLUGINS:-tables-filter tinymce}

  envoy:
    image: envoyproxy/envoy:v1.35-latest
    command: [ "-c", "/etc/envoy/envoy.yaml", "--log-level", "info" ]
    volumes:
      - ./.docker/envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "8080:8080"
      - "9901:9901"
    depends_on: [ httpbin ]

  httpbin:
    image: ghcr.io/mccutchen/go-httpbin
    expose: [ "8080" ]

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.3
    ports:
      - '9100:9100'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_LOG_CONSOLE_COLOR: 'true'
      KC_HTTP_PORT: 9100
    entrypoint: /bin/sh
    command:
      - -c
      - |
        set -ex

        /opt/keycloak/bin/kc.sh start-dev --import-realm # Start Keycloak in dev mode and import the realm
    volumes:
      - ./.docker/keycloak_config/:/opt/keycloak/data/import/:ro

  authz:
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
          cpus: "1"
    entrypoint: lightbridge-authz
    command:
      - serve
      - --config
      - /tmp/config.yaml
    build:
      context: .
    volumes:
      - ./.docker/authz/container.yaml:/tmp/config.yaml:ro
    environment:
      RUST_LOG: debug
    ports:
      - "3000"
      - "3001"
    healthcheck:
      test: [ "CMD", "/usr/local/bin/lightbridge-authz-healthcheck" ]


volumes:
  postgresql_data:
    driver: local
