[licenses]
unused-allowed-license = "warn"
confidence-threshold = 0.95
allow = [
    "Zlib",
    "ISC",
    "Unicode-3.0",
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0"
]

[[licenses.clarify]]
crate = "jwks"
expression = "MIT"
license-files = [
    { path = "LICENSE", hash = 0xeae77759 },
]

[advisories]
ignore = [
    "RUSTSEC-2025-0052",
    "RUSTSEC-2023-0071",
]
