---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lightbridge-authz-config
  namespace: test
data:
  config.yaml: |
    server:
      rest:
        address: "0.0.0.0"
        port: 3000
      grpc:
        address: "0.0.0.0"
        port: 3001
    logging:
      level: "info"
    database:
      url: "postgres://postgres:postgres@postgresql.test.svc.cluster.local:5432/lightbridge_authz"
      pool_size: 10
    oauth2:
      jwks_url: "http://keycloak.test.svc.cluster.local:9100/realms/dev/protocol/openid-connect/certs"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightbridge-authz
  namespace: test
  labels:
    app: lightbridge-authz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lightbridge-authz
  template:
    metadata:
      labels:
        app: lightbridge-authz
    spec:
      containers:
      - name: lightbridge-authz
        image: ghcr.io/dericko681/lightbridge-authz1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: rest
          containerPort: 3000
          protocol: TCP
        - name: grpc
          containerPort: 3001
          protocol: TCP
        env:
        - name: RUST_LOG
          value: "info"
        - name: CONFIG_PATH
          value: "/app/config/config.yaml"
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: lightbridge-authz-config
---
apiVersion: v1
kind: Service
metadata:
  name: lightbridge-authz
  namespace: test
  labels:
    app: lightbridge-authz
spec:
  type: ClusterIP
  ports:
  - name: rest
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: grpc
    port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: lightbridge-authz
