[package]
name = "lightbridge-authz"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
axum.workspace = true
chrono.workspace = true
rmcp = { workspace = true, features = ["transport-streamable-http-server"] }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
lightbridge-authz-api.workspace = true
lightbridge-authz-api-key.workspace = true
lightbridge-authz-bearer.workspace = true
lightbridge-authz-core = { workspace = true, features = ["axum"] }
lightbridge-authz-rest.workspace = true
mimalloc.workspace = true
sqlx.workspace = true
