-- ADR-0012 Decision 7 / #423: a real, CAS-consuming `device_authorizations` table backing RFC
-- 8628's device authorization grant, replacing `NoDeviceCodeStore`
-- (`crates/lightbridge-authz-rest/src/oauth2_op/noop_stores.rs`), which was a permanent no-op.
--
-- Column shape is exactly what ADR-0012 Decision 7 specified: id, device_code, user_code,
-- client_id, scope, status, subject, expires_at, interval_secs, last_polled_at (plus the ordinary
-- created_at every other table here carries).
--
-- ADR-0038 exception note: added to AGENTS.md's "genuinely not migratable to cratestack" list
-- alongside `signing_keys`/`project_members`/`exchange_refresh_tokens`, on the identical grounds
-- `exchange_refresh_tokens` already established -- `consume_device_authorization` must atomically
-- claim a device code exactly once across concurrent polling requests via
-- `UPDATE ... WHERE status = '<expected>' ... RETURNING`, a single-statement CAS cratestack's
-- generated CRUD surface has no way to express.
--
-- `id` is minted via `lightbridge_authz_core::cuid::cuid2()` (ADR-0039) -- never a second
-- `Uuid::new_v4()`/`gen_random_uuid()` call site. `device_code`/`user_code` are opaque `TEXT`,
-- never shape-validated, never sorted/paginated by (same ADR) -- `id` remains the row's real
-- identifier; `user_code` is a display/pairing code (RFC 8628 §6.1), not an id in ADR-0039's
-- sense, and is deliberately NOT cuid2-shaped (see `docs/adr/0012-*.md` Decision 7).
--
-- `status`: 'pending' (freshly issued, awaiting user action) -> 'approved'/'denied' (the
-- verification-page outcome, a CAS transition guarded by `WHERE status = 'pending'`) ->
-- 'consumed' (the CLI's poll that redeemed an approved/denied row exactly once, a second CAS
-- transition guarded by `WHERE status IN ('approved', 'denied')`). 'expired' is reserved in the
-- CHECK constraint for a possible future background sweep but is NEVER written by this migration's
-- Rust code today -- expiry is enforced read-time-only, exactly like `exchange_refresh_tokens`:
-- every read path (`find_active_device_authorization_by_device_code`/`..._by_user_code`) filters
-- `expires_at > now()` and treats a stale row as absent. A stuck `pending` row past its
-- `expires_at` is therefore never proactively cleaned up -- it simply stops being observable via
-- any read path, and remains in the table until a real GC job (not part of this ticket) removes
-- it. Document this limitation here rather than implying full cleanup.
--
-- `subject`: the resolved Keycloak `sub`, set only on the CAS transition to 'approved' -- never
-- present on a still-`pending` row, matching ADR-0012 Decision 7 verbatim.
--
-- `user_code` charset (RFC 8628 §6.1): generated by
-- `crates/lightbridge-authz-rest/src/oauth2_op/device_store.rs`'s `generate_user_code` as
-- Crockford-style base32 (excludes I/L/O/U to avoid visual ambiguity), always upper-cased at
-- generation and at lookup time, so the UNIQUE index below also serves as the case-insensitive
-- comparison's backing index -- no separate `citext`/functional index needed.
CREATE TABLE device_authorizations (
    id TEXT PRIMARY KEY,
    device_code TEXT NOT NULL UNIQUE,
    user_code TEXT NOT NULL,
    client_id TEXT NOT NULL,
    scope TEXT,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'approved', 'denied', 'consumed', 'expired')),
    subject TEXT,
    interval_secs INTEGER NOT NULL DEFAULT 5,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    last_polled_at TIMESTAMPTZ,
    -- `subject` is set once, on the pending->approved CAS transition, and survives the later
    -- approved->consumed CAS transition unchanged (consume_device_authorization only flips
    -- `status`, never touches `subject`) -- so a `consumed` row that started as `approved` keeps
    -- its subject too. Only `pending`/`denied` rows must never carry one.
    CONSTRAINT device_authorizations_subject_only_when_approved
        CHECK (status IN ('approved', 'consumed') OR subject IS NULL)
);

-- Own index for `get_by_user_code` (RFC 8628 §6.1's verification-page submission path) -- a table
-- scan on every submitted user_code is not acceptable. UNIQUE doubles as the collision guard the
-- ticket's Risks table calls for ("unique index + retry-on-conflict at insert time").
CREATE UNIQUE INDEX idx_device_authorizations_user_code ON device_authorizations (user_code);

-- Backs both read paths' `expires_at > now()` filter.
CREATE INDEX idx_device_authorizations_expires_at ON device_authorizations (expires_at);
