[package]
name = "lightbridge-authz-grpc"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tonic.workspace = true
lightbridge-authz-core.workspace = true
lightbridge-authz-proto.workspace = true