---
apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: self-service-config
  namespace: envoy-gateway-system
data:
  config.yaml: |
    server:
      rest:
        address: "0.0.0.0"
        port: 3000
      grpc:
        address: "0.0.0.0"
        port: 3001
    logging:
      level: "info"
    database:
      url: "postgres://postgres:postgres@postgresql:5432/self-service-app"
      pool_size: 10
    oauth2:
      jwks_url: "http://keycloak.envoy-gateway-system.svc.cluster.local:8080/realms/master/protocol/openid-connect/certs"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-service-app
  namespace: envoy-gateway-system
  labels:
    app: self-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-service-app
  template:
    metadata:
      labels:
        app: self-service-app
    spec:
      containers:
      - name: self-service-app
        image: ghcr.io/dericko681/self-service-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: rest
          containerPort: 3000
          protocol: TCP
        - name: grpc
          containerPort: 3001
          protocol: TCP
        env:
        - name: RUST_LOG
          value: "info"
        - name: CONFIG_PATH
          value: "/app/config/config.yaml"
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: self-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: self-service-svc
  namespace: envoy-gateway-system
  labels:
    app: self-service-app
spec:
  type: ClusterIP
  ports:
  - name: rest
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: grpc
    port: 3001
    targetPort: 3001
    protocol: TCP
    appProtocol: grpc
  selector:
    app: self-service-app
    