server:
  rest:
    address: "0.0.0.0"
    port: 3000
  grpc:
    address: "0.0.0.0"
    port: 3001
logging:
  level: "info"
database:
  url: "postgres://postgres:postgres@localhost:5432/lightbridge_authz"
  pool_size: 10
oauth2:
  jwks_url: "http://localhost:9100/realms/dev/protocol/openid-connect/certs"
