name: Container Build
runs:
  using: composite
  steps:
    - id: docker-setup
      uses: ./.github/actions/setup-docker
      with:
        app-version: ${{ github.sha }}
        image-name: ${{ github.repository }}
    - name: Build and push image
      uses: docker/build-push-action@v6.19.2
      with:
        context: .
        file: Dockerfile
        target: runtime
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.docker-setup.outputs.tags }}
        labels: ${{ steps.docker-setup.outputs.labels }}
        annotations: ${{ steps.docker-setup.outputs.annotations }}
        provenance: true
        sbom: true
