name: Container Build
inputs:
  ghcr-token:
    description: Token for GHCR login
    required: true
runs:
  using: composite
  steps:
    - uses: docker/setup-buildx-action@8d2750c
    - name: Log in to GHCR
      uses: docker/login-action@5e57cd1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr-token }}
    - name: Build and push image
      uses: docker/build-push-action@d5c5c38c1a483ee1fc40b1079a1c41ef1f26d006
      with:
        context: .
        file: Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ github.repository_owner }}/lightbridge-authz:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/lightbridge-authz:latest
