[package]
name = "lightbridge-authz-proto"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
prost-types.workspace = true
envoy-types.workspace = true
