[package]
name = "lightbridge-authz-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true
envoy-types.workspace = true

[build-dependencies]
tonic-build.workspace = true
