name: Cargo Deny
inputs:
  check:
    description: cargo-deny command to run
    required: true
runs:
  using: composite
  steps:
    - uses: ./.github/actions/rust-setup
    - shell: bash
      run: |
        if ! command -v cargo-deny >/dev/null; then
          cargo install --locked cargo-deny
        fi
        cargo deny check ${{ inputs.check }}
