name: Cargo Deny
inputs:
  check:
    description: cargo-deny command to run
    required: true
runs:
  using: composite
  steps:
    - uses: ./.github/actions/rust-setup
    - shell: bash
      run: cargo deny check ${{ inputs.check }}
