name: GH Pages Deploy
description: Publish a directory to GitHub Pages via gh-pages branch.
inputs:
  publish-dir:
    description: Directory to deploy
    required: true
  target-branch:
    description: Branch that backs GitHub Pages
    required: false
    default: gh-pages
  commit-message:
    description: Commit message for gh-pages updates
    required: false
    default: Deploy Helm chart packages
  github-token:
    description: Token used to push to GitHub Pages
    required: true
runs:
  using: composite
  steps:
    - uses: peaceiris/actions-gh-pages@e9c66a37f080288a11235e32cbe2dc5fb3a679cc
      with:
        publish_dir: ${{ inputs.publish-dir }}
        publish_branch: ${{ inputs.target-branch }}
        commit_message: ${{ inputs.commit-message }}
        github_token: ${{ inputs.github-token }}
