global:
  tlsSecretName: lightbridge-authz-tls
  authz:
    image:
      version: "0.6.2"
      repository: "ghcr.io/adorsys-gis/lightbridge-authz"
  authz_mcp:
    image:
      version: "0.6.2"
      repository: "ghcr.io/adorsys-gis/lightbridge-authz-mcp"
  authz_usage:
    image:
      version: "0.6.2"
      repository: "ghcr.io/adorsys-gis/lightbridge-authz-usage"

  tls:
    enabled: true
    apiCommonName: lightbridge-authz-api
    opaCommonName: lightbridge-authz-opa
    usageCommonName: lightbridge-authz-usage
    job:
      enabled: true
      image:
        repository: docker.io/bitnami/kubectl
        tag: 1.29.4
      restartPolicy: OnFailure
      backoffLimit: 3
      ttlSecondsAfterFinished: 300
      annotations: { }
      labels: { }
      serviceAccount:
        create: true
        automount: true
      role:
        create: true
      addKubectlOpenssl: true

api:
  enabled: true
  controllers:
    main:
      replicas: 1
      containers:
        authz:
          args:
            - api
            - --config-path
            - /etc/lightbridge/config.yaml
  persistence:
    tls:
      name: lightbridge-authz-tls

opa:
  enabled: true
  controllers:
    main:
      replicas: 2
      containers:
        authz:
          args:
            - opa
            - --config-path
            - /etc/lightbridge/config.yaml
  persistence:
    tls:
      name: lightbridge-authz-tls

usage:
  enabled: true
  persistence:
    tls:
      name: lightbridge-authz-usage-tls

mcp:
  enabled: true
  persistence:
    tls:
      name: lightbridge-authz-mcp-tls


rawRessources: [ ]