global:
  tlsSecretName: lightbridge-authz-tls
  tls:
    enabled: true
    mountPath: /etc/lightbridge/tls
    apiCommonName: lightbridge-authz-api
    opaCommonName: lightbridge-authz-opa
    usageCommonName: lightbridge-authz-usage
    job:
      enabled: true
      image:
        repository: docker.io/bitnami/kubectl
        tag: 1.29.4
      restartPolicy: OnFailure
      backoffLimit: 3
      ttlSecondsAfterFinished: 300
      annotations: {}
      labels: {}
      serviceAccount:
        create: true
        name:
        automount: true
      role:
        create: true
        name:
      addKubectlOpenssl: true

api:
  enabled: true
  persistence:
    tls:
      name: lightbridge-authz-tls

opa:
  enabled: true
  persistence:
    tls:
      name: lightbridge-authz-tls

usage:
  enabled: true
  persistence:
    tls:
      name: lightbridge-authz-tls

migration:
  enabled: true
  secrets:
    secret:
      stringData:
        DATABASE_URL: "postgres://postgres:postgres@postgresql:5432/lightbridge_authz"
        OPA_PASSWORD: "change-me"
