apiVersion: v2
name: lightbridge-authz-usage
description: Kubernetes deployment for the Lightbridge Authz Usage service

type: application
version: 0.6.6
appVersion: "0.6.6"
icon: https://adorsys.com/favicon.svg?v=05f867cc1aa036716c10a6c1d4ad6365
home: https://github.com/ADORSYS-GIS/lightbridge-authz
kubeVersion: ">=1.20.0-0"
keywords:
  - usage
  - otel
  - timescale
  - telemetry
sources:
  - https://github.com/ADORSYS-GIS/lightbridge-authz

dependencies:
  - name: common
    version: "4.6.2"
    repository: https://bjw-s-labs.github.io/helm-charts
