enabled: true

global:
  authz_usage:
    image:
      version: "0.6.0"
      repository: "ghcr.io/adorsys-gis/lightbridge-authz-usage"

controllers:
  main:
    type: deployment
    replicas: 1
    containers:
      authz:
        image:
          repository: "{{ .Values.global.authz_usage.image.repository }}"
          tag: "{{ .Values.global.authz_usage.image.version }}"
          pullPolicy: IfNotPresent
        args:
          - serve
          - --config-path
          - /etc/lightbridge/config.yaml
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        env:
          DATABASE_URL:
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DATABASE_URL

  migrate:
    type: job
    job:
      backoffLimit: 3
    annotations:
      "helm.sh/hook": post-install,post-upgrade
      "helm.sh/hook-weight": "-5"
      "helm.sh/hook-delete-policy": hook-succeeded
    containers:
      authz:
        image:
          repository: "{{ .Values.global.authz_usage.image.repository }}"
          tag: "{{ .Values.global.authz_usage.image.version }}"
          pullPolicy: IfNotPresent
        args:
          - migrate
          - --config-path
          - /etc/lightbridge/config.yaml
        env:
          DATABASE_URL:
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DATABASE_URL

configMaps:
  config:
    enabled: true
    data:
      config.yaml: |-
        logging:
          level: info
        database:
          url: "${DATABASE_URL}"
          pool_size: 10
        otel:
          enabled: true
          otlp_endpoint: http://localhost:4317
          service_name: lightbridge-authz-usage
        server:
          usage:
            address: 0.0.0.0
            port: 3000
            tls:
              cert_path: /etc/lightbridge/tls/usage.crt
              key_path: /etc/lightbridge/tls/usage.key


service:
  authz:
    controller: main
    ports:
      http:
        port: 3000

persistence:
  config:
    enabled: true
    type: configMap
    identifier: config
    advancedMounts:
      main:
        authz:
          - path: /etc/lightbridge/config.yaml
            subPath: config.yaml
            readOnly: true
      migrate:
        authz:
          - path: /etc/lightbridge/config.yaml
            subPath: config.yaml
            readOnly: true
  tls:
    enabled: true
    type: secret
    name: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-tls'
    globalMounts:
      - path: /etc/lightbridge/tls
        readOnly: true

