//! LoC rationale: This single trait implementation block (`impl schema::procedures::ProcedureRegistry for Procedures`) carries ~50 procedure handlers generated by cratestack. Rust does not allow splitting a single trait implementation block across multiple files.

use std::sync::Arc;

use cratestack::{CratestackContext, CratestackError};
use lightbridge_authz_api::schema;
use lightbridge_authz_core::{CreateAccount, CreateApiKey, RotateApiKey};

use crate::{
    budget_convert::{
        resolve_augmentation_requests_page_size, to_schema_augmentation_request,
        to_schema_augmentation_request_page, to_schema_decision,
    },
    budget_services::{BUDGET_POLICY_EVALUATION_BUDGET, BUDGET_POLICY_SET_ID},
    convert::*,
    error_convert::{budget_error_to_cratestack_error, to_cratestack_error},
    handlers::AuthzStoreImpl,
    identity_directory, my_access, platform_roles_directory,
    reset_schedule_convert::{
        parse_amount_micros, parse_run_at_or_default, parse_schedule_anchor,
        to_schema_budget_reset_schedule, to_schema_reset_schedule_run_result,
    },
    session_directory,
};

/// RPC procedure registry (ADR-0003 item 4). Every procedure delegates to the hand-written sqlx in
/// `AuthzStoreImpl`/`StoreRepo` (tenant-scoped by account ownership or a `project_members` row,
/// ADR-0006), never cratestack's `run_in_tx`, so the chained-write deadlock in cratestack-pg 0.4.9
/// (ADR-0003, "Known cratestack-pg 0.4.9 bugs", item 1) cannot occur. `db` is intentionally unused:
/// the generated CRUD client speaks over cratestack's own sqlx pool (a different sqlx major than
/// this workspace's), so the procedures use the pre-migration repository pool for their writes.
///
/// `policy_store` (ADR-0007) is the one exception to "delegates to `AuthzStoreImpl`/`StoreRepo`" --
/// the budget policy activation/status procedures below delegate to
/// [`lightbridge_authz_budget::PolicyStore`] instead, which owns its own persistence against the
/// same underlying database.
///
/// `refill_service`/`review_service` (#191, PR 3.4) are the same shape of exception: the
/// self-service refill and admin review-queue procedures delegate to
/// [`lightbridge_authz_budget::RefillService`]/[`lightbridge_authz_budget::ReviewService`], which
/// each own their own persistence (`BudgetRepo`/`AugmentationRepo`) against the same underlying
/// database, constructed once at server startup alongside `policy_store` -- see
/// `start_api_server`.
#[derive(Clone)]
pub struct Procedures {
    /// Which listener this registry is mounted behind (`SERVICE_API` or `SERVICE_BUDGET`), for
    /// `getBuildInfo` (#573). One registry type serves both routers, so the router that built it
    /// is the only thing that knows which service the caller actually reached -- deriving it at
    /// call time is impossible, and defaulting it would let `authz-budget` report itself as
    /// `authz-api` in the one screen built to detect exactly that class of mismatch.
    service: &'static str,
    issuer: Arc<AuthzStoreImpl>,
    policy_store: Arc<lightbridge_authz_budget::PolicyStore>,
    refill_service: Arc<lightbridge_authz_budget::RefillService>,
    review_service: Arc<lightbridge_authz_budget::ReviewService>,
    /// The direct-read/grant/revoke surface (`getMyBudgetBalance`/`getBudgetBalance`/
    /// `listMyBudgetGrants`/`listBudgetGrants`/`grantBudget`/`revokeBudgetGrant`) shares this
    /// `BudgetRepo` handle rather than going through `refill_service`/`review_service` -- those
    /// two own their own private `BudgetRepo` internally for the self-service/review flows, but
    /// neither exposes a read-only balance/ledger query surface, so this field is a second,
    /// independent handle against the SAME underlying database (constructed once at server
    /// startup, see `start_api_server`).
    budget_repo: Arc<lightbridge_authz_budget::repo::BudgetRepo>,
    /// The budget reset scheduler (ADR-0032). The SAME instance the `authz-budget` interval task
    /// drives (see `start_budget_server`), not a second one built for the RPC surface: a dry run
    /// and a real tick must be the same code over the same state, or a preview could disagree with
    /// what the scheduler goes on to do. It owns its own `ResetScheduleRepo`, so the four CRUD
    /// procedures reach schedules through `reset_scheduler.schedules()` rather than a separate
    /// field.
    reset_scheduler: Arc<lightbridge_authz_budget::ResetScheduler>,
    /// This deployment's configured platform-role catalogue (ADR-0033) --
    /// `oauth2.rbac.role_permissions`' keys, or the built-in defaults when it is unset. The ONLY
    /// consumer is `grantPlatformRole`, which refuses a role absent from it: an unvalidated typo
    /// writes a row that confers nothing while looking exactly like a successful grant. Threaded
    /// in from config rather than read from a global, so a test can drive a deployment whose roles
    /// are not the built-in three.
    rbac_roles: Arc<Vec<String>>,
}

impl Procedures {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        service: &'static str,
        issuer: Arc<AuthzStoreImpl>,
        policy_store: Arc<lightbridge_authz_budget::PolicyStore>,
        refill_service: Arc<lightbridge_authz_budget::RefillService>,
        review_service: Arc<lightbridge_authz_budget::ReviewService>,
        budget_repo: Arc<lightbridge_authz_budget::repo::BudgetRepo>,
        reset_scheduler: Arc<lightbridge_authz_budget::ResetScheduler>,
        rbac_roles: Arc<Vec<String>>,
    ) -> Self {
        Self {
            service,
            issuer,
            policy_store,
            refill_service,
            review_service,
            budget_repo,
            reset_scheduler,
            rbac_roles,
        }
    }
}

impl schema::procedures::ProcedureRegistry for Procedures {
    fn create_account(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::create_account::Args,
        _authorized: schema::procedures::create_account::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::create_account::Output, CratestackError>,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let default_quota = args.args.defaultQuota;
        let name = args.args.name;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let account = issuer
                .create_account(
                    &subject,
                    CreateAccount {
                        default_quota,
                        name,
                    },
                )
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_account(account))
        }
    }

    /// The admin-targets-an-arbitrary-subject account bootstrap (#720). Structurally shaped like
    /// `revoke_subject_sessions` below, not like `create_account` above: the target subject comes
    /// from `args`, not from `ctx` -- see `AuthzStoreImpl::provision_account`'s doc comment for the
    /// full design rationale. Permission enforcement (`account:provision`) already ran in the
    /// `rpc_authorize` middleware before dispatch reached this handler; `_caller` below is purely a
    /// "someone authenticated is calling" null-check, same as `revoke_subject_sessions`'s own.
    fn provision_account(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::provision_account::Args,
        _authorized: schema::procedures::provision_account::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::provision_account::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let caller = subject_from_ctx(ctx);
        let target_subject = args.args.subject;
        let email = args.args.email;
        let name = args.args.name;
        async move {
            let _caller = caller
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let account = issuer
                .provision_account(&target_subject, &email, name.as_deref())
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_account(account))
        }
    }

    fn update_account_default_quota(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::update_account_default_quota::Args,
        _authorized: schema::procedures::update_account_default_quota::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::update_account_default_quota::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let account_id = args.args.accountId;
        let default_quota = args.args.defaultQuota;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let account = issuer
                .update_account_default_quota(&subject, &account_id, default_quota.as_deref())
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_account(account))
        }
    }

    fn update_account_name(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::update_account_name::Args,
        _authorized: schema::procedures::update_account_name::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::update_account_name::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let account_id = args.args.accountId;
        let name = args.args.name;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let account = issuer
                .update_account_name(&subject, &account_id, name.as_deref())
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_account(account))
        }
    }

    fn rotate_api_key(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::rotate_api_key::Args,
        _authorized: schema::procedures::rotate_api_key::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::rotate_api_key::Output, CratestackError>,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let access_token = access_token_from_ctx(ctx);
        let key_id = args.args.keyId;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let secret = issuer
                .rotate_api_key(
                    &subject,
                    access_token.as_deref(),
                    &key_id,
                    RotateApiKey {
                        name: None,
                        expires_at: None,
                        grace_period_seconds: None,
                    },
                )
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_api_key_secret(secret))
        }
    }

    fn create_api_key(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::create_api_key::Args,
        _authorized: schema::procedures::create_api_key::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::create_api_key::Output, CratestackError>,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let access_token = access_token_from_ctx(ctx);
        let input = args.args;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let secret = issuer
                .create_api_key(
                    &subject,
                    access_token.as_deref(),
                    &input.projectId,
                    CreateApiKey {
                        name: input.name,
                        expires_at: Some(input.expiresAt),
                        billing_plan: input.billingPlan,
                    },
                )
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_api_key_secret(secret))
        }
    }

    /// Read-only: the operator-configured billing-plan catalogue `createApiKey` validates
    /// `billingPlan` against (see that procedure's doc comment in `authz.cstack`). No DB access --
    /// `AuthzStoreImpl::billing_plans` returns the in-memory `Billing` config loaded at startup.
    fn list_billing_plans(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        _args: schema::procedures::list_billing_plans::Args,
        _authorized: schema::procedures::list_billing_plans::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::list_billing_plans::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        async move {
            let _subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            Ok(to_schema_billing_plans(issuer.billing_plans()))
        }
    }

    /// Read-only: the operator-configured AI-model catalogue a `Project.allowedModels` editor
    /// renders (see that procedure's doc comment in `authz.cstack`). No DB access --
    /// `AuthzStoreImpl::model_catalog` returns the in-memory `ModelCatalog` config loaded at
    /// startup. Mirrors `list_billing_plans` above.
    fn list_model_catalog(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        _args: schema::procedures::list_model_catalog::Args,
        _authorized: schema::procedures::list_model_catalog::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::list_model_catalog::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        async move {
            let _subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            Ok(to_schema_model_catalog(issuer.model_catalog()))
        }
    }

    fn disable_account(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::disable_account::Args,
        _authorized: schema::procedures::disable_account::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::disable_account::Output, CratestackError>,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let account_id = args.args.accountId;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let account = issuer
                .disable_account(&subject, &account_id)
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_account(account))
        }
    }

    fn enable_account(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::enable_account::Args,
        _authorized: schema::procedures::enable_account::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::enable_account::Output, CratestackError>,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let account_id = args.args.accountId;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let account = issuer
                .enable_account(&subject, &account_id)
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_account(account))
        }
    }

    fn disable_project(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::disable_project::Args,
        _authorized: schema::procedures::disable_project::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::disable_project::Output, CratestackError>,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let project_id = args.args.projectId;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let project = issuer
                .disable_project(&subject, &project_id)
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_project(project))
        }
    }

    fn enable_project(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::enable_project::Args,
        _authorized: schema::procedures::enable_project::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::enable_project::Output, CratestackError>,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let project_id = args.args.projectId;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let project = issuer
                .enable_project(&subject, &project_id)
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_project(project))
        }
    }

    fn set_default_project(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::set_default_project::Args,
        _authorized: schema::procedures::set_default_project::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::set_default_project::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let project_id = args.args.projectId;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let project = issuer
                .set_default_project(&subject, &project_id)
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_project(project))
        }
    }

    fn set_project_quota(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::set_project_quota::Args,
        _authorized: schema::procedures::set_project_quota::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::set_project_quota::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let project_id = args.args.projectId;
        let project_quota = args.args.projectQuota;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let project = issuer
                .set_project_quota(&subject, &project_id, project_quota.as_deref())
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_project(project))
        }
    }

    fn set_project_allowed_models(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::set_project_allowed_models::Args,
        _authorized: schema::procedures::set_project_allowed_models::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::set_project_allowed_models::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let project_id = args.args.projectId;
        let allowed_models = allowed_models_from_json_arg(args.args.allowedModels);
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let project = issuer
                .set_project_allowed_models(&subject, &project_id, allowed_models)
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_project(project))
        }
    }

    fn set_project_model_policy(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::set_project_model_policy::Args,
        _authorized: schema::procedures::set_project_model_policy::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::set_project_model_policy::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let project_id = args.args.projectId;
        let model_policy = args.args.modelPolicy;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let project = issuer
                .set_project_model_policy(&subject, &project_id, &model_policy)
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_project(project))
        }
    }

    fn revoke_api_key(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::revoke_api_key::Args,
        _authorized: schema::procedures::revoke_api_key::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::revoke_api_key::Output, CratestackError>,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let key_id = args.args.keyId;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let key = issuer
                .revoke_api_key(&subject, &key_id)
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_api_key(key))
        }
    }

    /// Self-scoped, cross-project "expiring soon" aggregate (lightbridge-authz#436). Unlike every
    /// other procedure in this impl, this one DOES use `db` -- see the schema doc comment on
    /// `listMyExpiringApiKeys` for why: calling the generated `db.api_key()` delegate means this
    /// procedure's tenant isolation is enforced by the exact same compiled `@@allow("read", ...)`
    /// clause `model.ApiKey.list`/`get` already go through (`push_scoped_conditions` in
    /// cratestack-pg folds it into the query unconditionally, with no bypass), rather than a
    /// second, hand-written ownership join that could drift from the model's own policy.
    /// Soft-deleted rows are excluded the same way (the model's `@@soft_delete` filter, also
    /// applied unconditionally by the generated delegate) -- no explicit `deletedAt` check needed
    /// here.
    fn list_my_expiring_api_keys(
        &self,
        db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::list_my_expiring_api_keys::Args,
        _authorized: schema::procedures::list_my_expiring_api_keys::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::list_my_expiring_api_keys::Output,
            CratestackError,
        >,
    > + Send {
        let within_days = args.args.withinDays;
        async move {
            let within_days = clamp_expiring_soon_window_days(within_days);
            let now = chrono::Utc::now();
            let cutoff = now + chrono::Duration::days(within_days);
            // Three separate `.where_(...)` calls, not one `.and()`-chained expression:
            // `FindMany`/`ScopedFindMany` combine every entry in its `filters: Vec<FilterExpr>`
            // with `AND` when building the query (`push_filter_query`,
            // cratestack-sqlx/src/query/support/filter.rs), so this is equivalent to (and simpler
            // than) chaining `.and()` on the `Filter` values `eq`/`gt`/`lte` return.
            let keys = db
                .api_key()
                .find_many()
                .where_(schema::api_key::status().eq("active".to_string()))
                .where_(schema::api_key::expiresAt().gt(now))
                .where_(schema::api_key::expiresAt().lte(cutoff))
                .order_by(schema::api_key::expiresAt().asc())
                .limit(MAX_EXPIRING_API_KEYS_RESULTS)
                .run(ctx)
                .await?;
            Ok(keys)
        }
    }

    fn add_project_member(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::add_project_member::Args,
        _authorized: schema::procedures::add_project_member::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::add_project_member::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let project_id = args.args.projectId;
        let target_account_id = args.args.accountId;
        let role = args.args.role;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let project = issuer
                .add_project_member(&subject, &project_id, &target_account_id, role.as_deref())
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_project(project))
        }
    }

    fn remove_project_member(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::remove_project_member::Args,
        _authorized: schema::procedures::remove_project_member::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::remove_project_member::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let project_id = args.args.projectId;
        let target_account_id = args.args.accountId;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let project = issuer
                .remove_project_member(&subject, &project_id, &target_account_id)
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_project(project))
        }
    }

    fn set_project_member_role(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::set_project_member_role::Args,
        _authorized: schema::procedures::set_project_member_role::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::set_project_member_role::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let project_id = args.args.projectId;
        let target_account_id = args.args.accountId;
        let role = args.args.role;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let project = issuer
                .set_project_member_role(&subject, &project_id, &target_account_id, &role)
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_project(project))
        }
    }

    fn set_project_member_quota_tier(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::set_project_member_quota_tier::Args,
        _authorized: schema::procedures::set_project_member_quota_tier::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::set_project_member_quota_tier::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let project_id = args.args.projectId;
        let target_account_id = args.args.accountId;
        let quota_tier = args.args.quotaTier;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let project = issuer
                .set_project_member_quota_tier(
                    &subject,
                    &project_id,
                    &target_account_id,
                    quota_tier.as_deref(),
                )
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_project(project))
        }
    }

    /// The roster's only read path. Authorization is wider than the four mutations above -- any
    /// member may read, not just leads -- and lives in the repository's SQL; see
    /// `StoreRepo::list_project_roster`.
    fn list_project_roster(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::list_project_roster::Args,
        _authorized: schema::procedures::list_project_roster::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::list_project_roster::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let project_id = args.args.projectId;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let members = issuer
                .list_project_roster(&subject, &project_id)
                .await
                .map_err(to_cratestack_error)?;
            Ok(members.into_iter().map(to_schema_project_member).collect())
        }
    }

    fn delete_account_permanently(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::delete_account_permanently::Args,
        _authorized: schema::procedures::delete_account_permanently::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::delete_account_permanently::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let account_id = args.args.accountId;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let account = issuer
                .delete_account(&subject, &account_id)
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_account(account))
        }
    }

    /// Activates a budget policy (ADR-0007): either brand-new rule data (`ruleDataJson`) or a
    /// rollback to an already-existing revision (`revisionId`) --
    /// `docs/runbooks/roll-back-a-budget-policy.md`'s rollback flow needs the latter, since
    /// resubmitting the same rule data through the "new revision" path would collide with
    /// `budget_policy_revisions`' `UNIQUE (policy_set_id, policy_revision)` constraint. Exactly
    /// one of the two must be supplied.
    ///
    /// `policy_store` is bound once at server startup to [`BUDGET_POLICY_SET_ID`] -- there is
    /// genuinely only one policy set today. Rather than silently ignoring a caller-supplied
    /// `policySetId` that doesn't match it, this rejects the mismatch with a clear `BadRequest`:
    /// a caller who typos the policy set id should be told, not silently redirected to the one
    /// real set.
    fn activate_budget_policy(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::activate_budget_policy::Args,
        _authorized: schema::procedures::activate_budget_policy::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::activate_budget_policy::Output,
            CratestackError,
        >,
    > + Send {
        let policy_store = self.policy_store.clone();
        let subject = subject_from_ctx(ctx);
        let policy_set_id = args.args.policySetId;
        let rule_data_json = args.args.ruleDataJson;
        let revision_id = args.args.revisionId;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            if policy_set_id != BUDGET_POLICY_SET_ID {
                return Err(CratestackError::BadRequest(format!(
                    "unknown policySetId '{policy_set_id}' -- only '{BUDGET_POLICY_SET_ID}' \
                     exists today"
                )));
            }

            let active_revision = match (rule_data_json, revision_id) {
                (Some(json), None) => policy_store
                    .activate(&json, Some(&subject))
                    .await
                    .map_err(budget_error_to_cratestack_error)?,
                (None, Some(revision_id)) => policy_store
                    .activate_by_revision_id(&revision_id)
                    .await
                    .map_err(budget_error_to_cratestack_error)?,
                (Some(_), Some(_)) => {
                    return Err(CratestackError::BadRequest(
                        "exactly one of ruleDataJson or revisionId must be provided, not both"
                            .to_owned(),
                    ));
                }
                (None, None) => {
                    return Err(CratestackError::BadRequest(
                        "exactly one of ruleDataJson or revisionId must be provided".to_owned(),
                    ));
                }
            };

            Ok(schema::procedures::activate_budget_policy::Output {
                policySetId: policy_set_id,
                activePolicyRevision: active_revision,
            })
        }
    }

    /// Reports the revision genuinely serving `evaluate()` calls right now -- reads the live
    /// in-memory engine state directly (`PolicyStore::active_policy_revision`), no database
    /// round-trip needed. See the schema's `getBudgetPolicyStatus` doc comment for why this
    /// distinction (serving vs. most-recently-attempted) matters for the rollback runbook.
    fn get_budget_policy_status(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::get_budget_policy_status::Args,
        _authorized: schema::procedures::get_budget_policy_status::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::get_budget_policy_status::Output,
            CratestackError,
        >,
    > + Send {
        let policy_store = self.policy_store.clone();
        let subject = subject_from_ctx(ctx);
        let policy_set_id = args.args.policySetId;
        async move {
            let _subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            if policy_set_id != BUDGET_POLICY_SET_ID {
                return Err(CratestackError::BadRequest(format!(
                    "unknown policySetId '{policy_set_id}' -- only '{BUDGET_POLICY_SET_ID}' \
                     exists today"
                )));
            }

            Ok(schema::procedures::get_budget_policy_status::Output {
                policySetId: policy_set_id,
                activePolicyRevision: policy_store.active_policy_revision(),
            })
        }
    }

    /// Evaluates a proposed rule-data policy against a caller-supplied scenario, entirely in
    /// memory (#190, ADR-0007). Deliberately does NOT touch `self.policy_store` -- unlike every
    /// other method on this `impl`, this one constructs its own short-lived
    /// [`lightbridge_authz_budget::RuleDataEngine`] directly from the caller's `ruleDataJson`,
    /// calls `evaluate()` on it once, and discards it. There is no code path here capable of
    /// writing to `budget_policy_sets`/`budget_policy_revisions` (no `PolicyStore` reference to
    /// do so through) or to `budget_grants`/`budget_balances` (no repository reference to do so
    /// through either) -- "no side effects" holds by construction, not by discipline. See
    /// `crates/lightbridge-authz-rest/tests/budget_policy_simulate_tests.rs` for the row-count
    /// proof.
    fn simulate_budget_policy(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::simulate_budget_policy::Args,
        _authorized: schema::procedures::simulate_budget_policy::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::simulate_budget_policy::Output,
            CratestackError,
        >,
    > + Send {
        let subject = subject_from_ctx(ctx);
        let rule_data_json = args.args.ruleDataJson;
        let scenario_json = args.args.scenarioJson;
        let requested_amount_str = args.args.requestedAmountMicros;
        async move {
            let _subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            let requested_amount_micros: i64 = requested_amount_str.trim().parse().map_err(|_| {
                CratestackError::BadRequest(format!(
                    "requestedAmountMicros must be a valid integer, got '{requested_amount_str}'"
                ))
            })?;

            let facts: lightbridge_authz_budget::Facts = serde_json::from_str(&scenario_json)
                .map_err(|e| CratestackError::BadRequest(format!("invalid scenarioJson: {e}")))?;

            // A short-lived engine, constructed and discarded within this one call -- never
            // wired into `self.policy_store`, never persisted, never touches
            // budget_policy_sets/budget_policy_revisions.
            let engine = lightbridge_authz_budget::RuleDataEngine::new(
                &rule_data_json,
                BUDGET_POLICY_EVALUATION_BUDGET,
            )
            .map_err(budget_error_to_cratestack_error)?;

            let decision = lightbridge_authz_budget::PolicyEngine::evaluate(
                &engine,
                &facts,
                requested_amount_micros,
            )
            .await
            .map_err(budget_error_to_cratestack_error)?;

            Ok(to_schema_decision(decision))
        }
    }

    /// Self-service refill (#191, PR 3.4): a caller asks for more budget for
    /// `budgetAccountId`/`period`, and [`lightbridge_authz_budget::RefillService::request_refill`]
    /// decides -- immediately, or by queuing for a human -- without anyone hand-editing config.
    /// `as_of` is read from the real wall clock here, deliberately: this is the one place in the
    /// whole refill call chain a live `chrono::Utc::now()` read belongs, because this is live
    /// request handling (not a pure, unit-testable domain function -- `RefillRequest.as_of` is a
    /// caller-supplied parameter for exactly this reason, per that struct's own doc comment).
    ///
    /// ## The requester is persisted (#646)
    ///
    /// The authenticated subject is written to `budget_augmentation_requests.requested_by_user_id`
    /// and surfaced as `AugmentationRequest.requestedByUserId`, so the admin review queue can name
    /// who asked instead of only which account and which reviewer. There is no "request on behalf
    /// of" input and there must not be one: the recorded requester is always the caller, which is
    /// the only claim this field is allowed to make. It is an audit field -- nothing here or
    /// downstream makes an authorization decision from it.
    ///
    /// ## Authorization is `budget:self-refill` alone (#419)
    ///
    /// This procedure used to *additionally* refuse any caller whose validated token carried
    /// [`lightbridge_authz_bearer::CALLER_KIND_CLAIM`] equal to
    /// [`lightbridge_authz_bearer::API_KEY_CALLER_KIND`] (#191/#216) -- intended to keep a service
    /// account from self-refilling ("refills are OIDC users only"). #419 deleted that check: it
    /// fired on humans, not service accounts. `signing.rs`'s `access_token_extra` -- shared by
    /// both `ApiKeyJwtSigner::sign` (API keys) *and* `oauth2_op::store::TokenExchangeOpStore`'s
    /// `handle_token_exchange`/`handle_refresh_token` (the human-plane RFC 8693 exchange) --
    /// stamps this claim on every access token it mints, unconditionally, with no parameter to
    /// vary it by caller. So every human-plane token carried it too, and got refused by a message
    /// asserting the opposite of what was happening. It was also never load-bearing: under
    /// `oauth2.type: self` (this repo's shipped default) an API-key JWT carries no roles claim at
    /// all, so `rpc_authorize`/`CratestackAuthProvider` already refuses it for lacking
    /// `budget:self-refill` before this procedure ever runs; under `external`, tokens from the
    /// upstream IdP's own API-key exchange never carried the claim to begin with (`docs/rbac.md`).
    /// The service-account exclusion this was written for is already correctly expressed by the
    /// permission gate alone: a service account never performs an OIDC dashboard login, so it
    /// never holds a role granting `budget:self-refill` in the first place. See
    /// `crates/lightbridge-authz-rest/tests/token_exchange_tests.rs`'s
    /// `request_refill_accepts_a_real_human_plane_token_that_still_carries_the_stale_api_key_signal`
    /// for the regression coverage minted through the real signing path (not a hand-built
    /// context) that would have caught this before it shipped.
    fn request_budget_refill(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::request_budget_refill::Args,
        _authorized: schema::procedures::request_budget_refill::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::request_budget_refill::Output,
            CratestackError,
        >,
    > + Send {
        let refill_service = self.refill_service.clone();
        let subject = subject_from_ctx(ctx);
        let input = args.args;
        async move {
            // #646: the caller's subject is no longer merely proof that someone is authenticated
            // -- it is persisted onto the request row as `requested_by_user_id` so a decided
            // request stays attributable to a person. Still fail-closed and still never trusted
            // as authorization: `rpc_authorize` has already gated this op-id on
            // `budget:self-refill` before this procedure runs, and nothing below branches on the
            // value.
            let requested_by_user_id = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            let period = lightbridge_authz_budget::Period::parse(&input.period)
                .map_err(budget_error_to_cratestack_error)?;

            // ADR-0015: required -- checked against the active policy's offered set
            // (`allowed_amounts_micros`) inside `RefillService::request_refill` itself.
            let requested_amount_raw = input.requestedAmountMicros.trim();
            let requested_amount_micros: i64 = requested_amount_raw.parse().map_err(|_| {
                CratestackError::BadRequest(format!(
                    "requestedAmountMicros must be a valid integer, got '{requested_amount_raw}'"
                ))
            })?;

            let request = lightbridge_authz_budget::RefillRequest {
                budget_account_id: input.budgetAccountId,
                account_id: input.accountId,
                project_id: input.projectId,
                period,
                idempotency_key: input.idempotencyKey,
                as_of: chrono::Utc::now(),
                requested_amount_micros,
                requested_by_user_id: Some(requested_by_user_id),
            };

            let created = refill_service
                .request_refill(request)
                .await
                .map_err(budget_error_to_cratestack_error)?;

            Ok(to_schema_augmentation_request(created))
        }
    }

    /// Read-only companion to [`Self::request_budget_refill`]: the self-service refill amounts
    /// currently offered by the active policy for `period` -- delegating to
    /// [`lightbridge_authz_budget::RefillService::refill_status`], which calls no policy engine
    /// and mutates nothing. `budgetAccountId` is derived from the authenticated subject exactly
    /// like [`Self::get_my_budget_balance`] (never a caller-supplied field, the same structural
    /// self-scoping guarantee), which is why `GetMyBudgetRefillLadderInput` has no target field
    /// either. No caller-kind refusal here -- unlike the mutation above, this is a pure read with
    /// no OIDC-human-only business rule of its own; the shared `budget:self-refill` RBAC gate is
    /// the entire authorization story for this op-id.
    fn get_my_budget_refill_ladder(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::get_my_budget_refill_ladder::Args,
        _authorized: schema::procedures::get_my_budget_refill_ladder::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::get_my_budget_refill_ladder::Output,
            CratestackError,
        >,
    > + Send {
        let refill_service = self.refill_service.clone();
        let subject = subject_from_ctx(ctx);
        let period_str = args.args.period;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            lightbridge_authz_budget::Period::parse(&period_str)
                .map_err(budget_error_to_cratestack_error)?;

            let status = refill_service
                .refill_status()
                .await
                .map_err(budget_error_to_cratestack_error)?;

            Ok(to_schema_my_budget_refill_ladder(
                subject, period_str, status,
            ))
        }
    }

    /// The admin review queue's read path (#191, PR 3.4; pagination added by #296), delegating
    /// to [`lightbridge_authz_budget::ReviewService::list_pending`]. `budgetAccountId: None`
    /// lists the whole cross-account queue; `Some` scopes to one account -- see that method's own
    /// doc comment.
    ///
    /// Paginated by `createdAt`, oldest-first, cursored via `after` -- see
    /// `authz.cstack`'s `ListPendingAugmentationRequestsInput` doc comment for why this queue
    /// keeps its pre-existing ASC order and uses `after` rather than `listMyBudgetGrants`'s
    /// `before`.
    fn list_pending_augmentation_requests(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::list_pending_augmentation_requests::Args,
        _authorized: schema::procedures::list_pending_augmentation_requests::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::list_pending_augmentation_requests::Output,
            CratestackError,
        >,
    > + Send {
        let review_service = self.review_service.clone();
        let subject = subject_from_ctx(ctx);
        let input = args.args;
        async move {
            let _subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            let page_size = resolve_augmentation_requests_page_size(input.limit);
            let requests = review_service
                .list_pending(input.budgetAccountId.as_deref(), input.after, page_size)
                .await
                .map_err(budget_error_to_cratestack_error)?;

            Ok(to_schema_augmentation_request_page(requests, page_size))
        }
    }

    /// The caller's own request history (#295's remaining half), delegating to
    /// [`lightbridge_authz_budget::RefillService::list_own_history`]. No target field on this
    /// input at all -- the target is always the caller's own budget account (`auth().id`), the
    /// same structural IDOR guard `getMyBudgetBalance`/`listMyBudgetGrants` already give. Returns
    /// every status, not filtered to `pending_review` the way
    /// `listPendingAugmentationRequests` is. Gated at `budget:read-own`.
    ///
    /// Paginated by `createdAt`, newest-first, cursored via `before` -- matching
    /// `listMyBudgetGrants`/`listBudgetGrants`'s own convention exactly (see
    /// `authz.cstack`'s `ListMyAugmentationRequestsInput` doc comment for why this, unlike the
    /// admin queue above, follows that precedent rather than the ASC/`after` shape).
    fn list_my_augmentation_requests(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::list_my_augmentation_requests::Args,
        _authorized: schema::procedures::list_my_augmentation_requests::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::list_my_augmentation_requests::Output,
            CratestackError,
        >,
    > + Send {
        let refill_service = self.refill_service.clone();
        let subject = subject_from_ctx(ctx);
        let input = args.args;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            let page_size = resolve_augmentation_requests_page_size(input.limit);
            let requests = refill_service
                .list_own_history(&subject, input.before, page_size)
                .await
                .map_err(budget_error_to_cratestack_error)?;

            Ok(to_schema_augmentation_request_page(requests, page_size))
        }
    }

    /// Approves a `pending_review` request (#191, PR 3.4), delegating to
    /// [`lightbridge_authz_budget::ReviewService::approve`]. The reviewing identity is the
    /// authenticated caller's own subject -- there is no separate "act on behalf of" input here,
    /// matching every other procedure in this file.
    fn approve_augmentation_request(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::approve_augmentation_request::Args,
        _authorized: schema::procedures::approve_augmentation_request::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::approve_augmentation_request::Output,
            CratestackError,
        >,
    > + Send {
        let review_service = self.review_service.clone();
        let subject = subject_from_ctx(ctx);
        let request_id = args.args.requestId;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            let reviewed = review_service
                .approve(&request_id, &subject)
                .await
                .map_err(budget_error_to_cratestack_error)?;

            Ok(to_schema_augmentation_request(reviewed))
        }
    }

    /// Rejects a `pending_review` request (#191, PR 3.4), delegating to
    /// [`lightbridge_authz_budget::ReviewService::reject`]. `reason` is non-optional in the
    /// schema (see `authz.cstack`'s `RejectAugmentationRequestInput` doc comment) as well as
    /// validated at runtime by `ReviewService::reject` itself -- this procedure adds no
    /// additional validation of its own, deliberately: one place owns the mandatory-reason rule.
    fn reject_augmentation_request(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::reject_augmentation_request::Args,
        _authorized: schema::procedures::reject_augmentation_request::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::reject_augmentation_request::Output,
            CratestackError,
        >,
    > + Send {
        let review_service = self.review_service.clone();
        let subject = subject_from_ctx(ctx);
        let request_id = args.args.requestId;
        let reason = args.args.reason;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            let reviewed = review_service
                .reject(&request_id, &subject, &reason)
                .await
                .map_err(budget_error_to_cratestack_error)?;

            Ok(to_schema_augmentation_request(reviewed))
        }
    }

    /// "Log out everywhere": revokes every active refresh-token session belonging to the
    /// authenticated caller. `input.reason` is accepted for audit-trail purposes only (not
    /// persisted anywhere today -- there is no session-revocation audit table, unlike the budget
    /// ledger) and never changes which subject is targeted. There is deliberately no subject
    /// field on this procedure's input at all: the target is always `auth().id`, never a
    /// caller-supplied value, which is what makes this procedure structurally incapable of being
    /// aimed at anyone but the caller -- see `revokeSubjectSessions` for the admin equivalent.
    /// Gated at `session:revoke-own` (`rpc_authorize.rs`).
    fn revoke_own_sessions(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        _args: schema::procedures::revoke_own_sessions::Args,
        _authorized: schema::procedures::revoke_own_sessions::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::revoke_own_sessions::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let revoked_count = issuer
                .revoke_sessions(&subject)
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_session_revocation_result(revoked_count))
        }
    }

    /// The offboarding kill switch: revokes every active refresh-token session for
    /// `input.accountId`, an operator-supplied target subject (`accounts.id` holds the JWT `sub`
    /// verbatim, ADR-0006). Previously the only way to do this was a manual SQL `UPDATE` against
    /// prod. `@allow(auth() != null)` only in the schema, same as the budget-policy/review
    /// procedures above -- there is no per-tenant ownership relation between an admin and an
    /// arbitrary target subject for a schema `@@allow` to check, so the entire authorization
    /// story is the RBAC gate: `session:revoke`, held only via `lightbridge-admin`'s `*` in the
    /// default role mapping (`docs/rbac.md`).
    fn revoke_subject_sessions(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::revoke_subject_sessions::Args,
        _authorized: schema::procedures::revoke_subject_sessions::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::revoke_subject_sessions::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let subject = subject_from_ctx(ctx);
        let target_account_id = args.args.accountId;
        async move {
            let _subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let revoked_count = issuer
                .revoke_sessions(&target_account_id)
                .await
                .map_err(to_cratestack_error)?;
            Ok(to_schema_session_revocation_result(revoked_count))
        }
    }

    /// Reads the caller's own current budget balance for `input.period`. There is no target
    /// field on this input at all -- the target is always `auth().id`, the same structural
    /// guarantee `revokeOwnSessions` gives for session revocation. Gated at `budget:read-own`.
    /// See `BalanceSnapshot::zero`'s doc comment for why "no balance row yet" synthesizes a
    /// zero-valued response rather than an error.
    fn get_my_budget_balance(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::get_my_budget_balance::Args,
        _authorized: schema::procedures::get_my_budget_balance::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::get_my_budget_balance::Output,
            CratestackError,
        >,
    > + Send {
        let budget_repo = self.budget_repo.clone();
        let subject = subject_from_ctx(ctx);
        let period_str = args.args.period;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let period = lightbridge_authz_budget::Period::parse(&period_str)
                .map_err(budget_error_to_cratestack_error)?;

            let snapshot = budget_repo
                .get_balance(&subject, &period)
                .await
                .map_err(budget_error_to_cratestack_error)?
                .unwrap_or_else(|| {
                    lightbridge_authz_budget::repo::BalanceSnapshot::zero(&subject, &period)
                });

            Ok(to_schema_budget_balance(snapshot))
        }
    }

    /// The admin equivalent of `getMyBudgetBalance`: reads any account's balance. Gated at
    /// `budget:read`.
    fn get_budget_balance(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::get_budget_balance::Args,
        _authorized: schema::procedures::get_budget_balance::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::get_budget_balance::Output,
            CratestackError,
        >,
    > + Send {
        let budget_repo = self.budget_repo.clone();
        let subject = subject_from_ctx(ctx);
        let budget_account_id = args.args.budgetAccountId;
        let period_str = args.args.period;
        async move {
            let _subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let period = lightbridge_authz_budget::Period::parse(&period_str)
                .map_err(budget_error_to_cratestack_error)?;

            let snapshot = budget_repo
                .get_balance(&budget_account_id, &period)
                .await
                .map_err(budget_error_to_cratestack_error)?
                .unwrap_or_else(|| {
                    lightbridge_authz_budget::repo::BalanceSnapshot::zero(
                        &budget_account_id,
                        &period,
                    )
                });

            Ok(to_schema_budget_balance(snapshot))
        }
    }

    /// The caller's own ledger history, paginated by `createdAt` (ADR-0039 -- never by id). No
    /// target field on this input, same structural guarantee as `getMyBudgetBalance`. Gated at
    /// `budget:read-own`.
    fn list_my_budget_grants(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::list_my_budget_grants::Args,
        _authorized: schema::procedures::list_my_budget_grants::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::list_my_budget_grants::Output,
            CratestackError,
        >,
    > + Send {
        let budget_repo = self.budget_repo.clone();
        let subject = subject_from_ctx(ctx);
        let input = args.args;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let page = list_budget_grants_page(
                &budget_repo,
                &subject,
                input.period,
                input.before,
                input.limit,
            )
            .await?;
            Ok(page)
        }
    }

    /// The admin equivalent of `listMyBudgetGrants`: any account's ledger history. Gated at
    /// `budget:audit-read`.
    fn list_budget_grants(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::list_budget_grants::Args,
        _authorized: schema::procedures::list_budget_grants::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::list_budget_grants::Output,
            CratestackError,
        >,
    > + Send {
        let budget_repo = self.budget_repo.clone();
        let subject = subject_from_ctx(ctx);
        let input = args.args;
        async move {
            let _subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let page = list_budget_grants_page(
                &budget_repo,
                &input.budgetAccountId,
                input.period,
                input.before,
                input.limit,
            )
            .await?;
            Ok(page)
        }
    }

    /// A direct admin grant, bypassing self-service policy evaluation. Delegates to the same
    /// `BudgetRepo::grant` transactional write path every other grant source uses, with
    /// `source = admin`. Gated at `budget:grant`.
    fn grant_budget(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::grant_budget::Args,
        _authorized: schema::procedures::grant_budget::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::grant_budget::Output, CratestackError>,
    > + Send {
        let budget_repo = self.budget_repo.clone();
        let subject = subject_from_ctx(ctx);
        let input = args.args;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            let period = lightbridge_authz_budget::Period::parse(&input.period)
                .map_err(budget_error_to_cratestack_error)?;
            let amount_micros: i64 = input.amountMicros.trim().parse().map_err(|_| {
                CratestackError::BadRequest(format!(
                    "amountMicros must be a valid integer, got '{}'",
                    input.amountMicros
                ))
            })?;

            let grant = budget_repo
                .grant(lightbridge_authz_budget::repo::GrantRequest {
                    budget_account_id: input.budgetAccountId,
                    account_id: input.accountId,
                    project_id: input.projectId,
                    period,
                    amount_micros,
                    source: lightbridge_authz_budget::GrantSource::Admin,
                    actor_id: Some(subject),
                    reason: input.reason,
                    policy_revision: None,
                    matched_rule_ids: None,
                    idempotency_key: input.idempotencyKey,
                    trigger_key: None,
                    expires_at: None,
                })
                .await
                .map_err(budget_error_to_cratestack_error)?;

            Ok(to_schema_budget_grant_entry(grant))
        }
    }

    /// The compensating-correction counterpart to `grantBudget` (ADR-0009: the ledger is
    /// append-only, so this never mutates `input.grantId`'s row -- it looks it up and writes a
    /// NEW `source = correction` row negating its amount). The correction's idempotency key is
    /// derived from `grantId` (`"revoke:{grantId}"`), so a repeated call for the same grant is
    /// idempotent rather than double-negating. Gated at `budget:revoke`.
    fn revoke_budget_grant(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::revoke_budget_grant::Args,
        _authorized: schema::procedures::revoke_budget_grant::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::revoke_budget_grant::Output,
            CratestackError,
        >,
    > + Send {
        let budget_repo = self.budget_repo.clone();
        let subject = subject_from_ctx(ctx);
        let grant_id = args.args.grantId;
        let reason = args.args.reason;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            let original = budget_repo
                .get_grant_by_id(&grant_id)
                .await
                .map_err(budget_error_to_cratestack_error)?;

            let correction = budget_repo
                .grant(lightbridge_authz_budget::repo::GrantRequest {
                    budget_account_id: original.budget_account_id,
                    account_id: original.account_id,
                    project_id: original.project_id,
                    period: original.period,
                    amount_micros: -original.amount_micros,
                    source: lightbridge_authz_budget::GrantSource::Correction,
                    actor_id: Some(subject),
                    reason: Some(reason),
                    policy_revision: None,
                    matched_rule_ids: None,
                    idempotency_key: Some(format!("revoke:{grant_id}")),
                    trigger_key: None,
                    expires_at: None,
                })
                .await
                .map_err(budget_error_to_cratestack_error)?;

            Ok(to_schema_budget_grant_entry(correction))
        }
    }

    /// Authors a new budget-policy revision WITHOUT activating it (ADR-0007). Delegates to
    /// `PolicyStore::create_revision`, which validates before writing, exactly mirroring
    /// `activateBudgetPolicy`'s "a bad revision never displaces a good one" property for the
    /// write path. Gated at `budget:policy-write`, kept distinct from `budget:policy-activate`.
    fn create_budget_policy_revision(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::create_budget_policy_revision::Args,
        _authorized: schema::procedures::create_budget_policy_revision::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::create_budget_policy_revision::Output,
            CratestackError,
        >,
    > + Send {
        let policy_store = self.policy_store.clone();
        let subject = subject_from_ctx(ctx);
        let policy_set_id = args.args.policySetId;
        let rule_data_json = args.args.ruleDataJson;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            if policy_set_id != BUDGET_POLICY_SET_ID {
                return Err(CratestackError::BadRequest(format!(
                    "unknown policySetId '{policy_set_id}' -- only '{BUDGET_POLICY_SET_ID}' \
                     exists today"
                )));
            }

            let new_revision = policy_store
                .create_revision(&rule_data_json, Some(&subject))
                .await
                .map_err(budget_error_to_cratestack_error)?;

            Ok(schema::procedures::create_budget_policy_revision::Output {
                policySetId: policy_set_id,
                revisionId: new_revision.id,
                policyRevision: new_revision.policy_revision,
            })
        }
    }

    /// Every reset schedule, oldest first. Gated at `budget:schedule-manage`.
    fn list_budget_reset_schedules(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        _args: schema::procedures::list_budget_reset_schedules::Args,
        _authorized: schema::procedures::list_budget_reset_schedules::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::list_budget_reset_schedules::Output,
            CratestackError,
        >,
    > + Send {
        let reset_scheduler = self.reset_scheduler.clone();
        let subject = subject_from_ctx(ctx);
        async move {
            let _subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            let schedules = reset_scheduler
                .schedules()
                .list()
                .await
                .map_err(budget_error_to_cratestack_error)?;
            Ok(schedules
                .into_iter()
                .map(to_schema_budget_reset_schedule)
                .collect())
        }
    }

    /// Authors a schedule, ALWAYS disabled (ADR-0032) -- there is no input field a caller could set
    /// to create an already-live global schedule. An explicit `nextRunAt` forces the first window
    /// onto a date the operator picks and must be in the future, so nobody can backdate one into
    /// firing immediately. Gated at `budget:schedule-manage`.
    fn create_budget_reset_schedule(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::create_budget_reset_schedule::Args,
        _authorized: schema::procedures::create_budget_reset_schedule::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::create_budget_reset_schedule::Output,
            CratestackError,
        >,
    > + Send {
        let reset_scheduler = self.reset_scheduler.clone();
        let subject = subject_from_ctx(ctx);
        let input = args.args;
        async move {
            let subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            let run_at_utc = parse_run_at_or_default(input.runAtUtc.as_deref())?;

            let schedule = reset_scheduler
                .schedules()
                .create(
                    lightbridge_authz_budget::NewBudgetResetSchedule {
                        name: input.name,
                        scope_kind: input
                            .scopeKind
                            .parse()
                            .map_err(budget_error_to_cratestack_error)?,
                        scope_id: input.scopeId,
                        cadence: input
                            .cadence
                            .parse()
                            .map_err(budget_error_to_cratestack_error)?,
                        anchor: parse_schedule_anchor(input.anchor)?,
                        run_at_utc,
                        amount_micros: parse_amount_micros(&input.amountMicros)?,
                        mode: input
                            .mode
                            .parse()
                            .map_err(budget_error_to_cratestack_error)?,
                        next_run_at: input.nextRunAt,
                    },
                    Some(&subject),
                    chrono::Utc::now(),
                )
                .await
                .map_err(budget_error_to_cratestack_error)?;

            Ok(to_schema_budget_reset_schedule(schedule))
        }
    }

    /// A partial update; an omitted field leaves its column alone. This is also the only way to
    /// flip `enabled`, which is what makes "create -> dry run -> enable" the enforced flow rather
    /// than a convention. Gated at `budget:schedule-manage`.
    fn update_budget_reset_schedule(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::update_budget_reset_schedule::Args,
        _authorized: schema::procedures::update_budget_reset_schedule::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::update_budget_reset_schedule::Output,
            CratestackError,
        >,
    > + Send {
        let reset_scheduler = self.reset_scheduler.clone();
        let subject = subject_from_ctx(ctx);
        let input = args.args;
        async move {
            let _subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            // `scopeId` is read only alongside `scopeKind`: the two move together, since the DB
            // CHECK requires `global` to carry no scopeId and every other kind to carry one.
            let scope = input
                .scopeKind
                .map(|kind| {
                    kind.parse::<lightbridge_authz_budget::ScheduleScopeKind>()
                        .map(|kind| (kind, input.scopeId.clone()))
                })
                .transpose()
                .map_err(budget_error_to_cratestack_error)?;

            let update = lightbridge_authz_budget::BudgetResetScheduleUpdate {
                name: input.name,
                scope,
                cadence: input
                    .cadence
                    .map(|c| c.parse())
                    .transpose()
                    .map_err(budget_error_to_cratestack_error)?,
                // `Some(None)` (clear the anchor) is unreachable over this wire shape -- an absent
                // `anchor` and an explicit null are the same value here -- so an omitted anchor
                // keeps the stored one, EXCEPT when the cadence becomes daily, where the repo
                // clears it (see `ResetScheduleRepo::update`).
                anchor: parse_schedule_anchor(input.anchor)?.map(Some),
                run_at_utc: input
                    .runAtUtc
                    .as_deref()
                    .map(lightbridge_authz_budget::parse_run_at_utc)
                    .transpose()
                    .map_err(budget_error_to_cratestack_error)?,
                amount_micros: input
                    .amountMicros
                    .as_deref()
                    .map(parse_amount_micros)
                    .transpose()?,
                mode: input
                    .mode
                    .map(|m| m.parse())
                    .transpose()
                    .map_err(budget_error_to_cratestack_error)?,
                enabled: input.enabled,
                next_run_at: input.nextRunAt,
            };

            let schedule = reset_scheduler
                .schedules()
                .update(&input.id, update, chrono::Utc::now())
                .await
                .map_err(budget_error_to_cratestack_error)?;

            Ok(to_schema_budget_reset_schedule(schedule))
        }
    }

    /// Deletes a schedule. The grants it already wrote stay in the append-only ledger (ADR-0009);
    /// this removes the future, never the past. Gated at `budget:schedule-manage`.
    fn delete_budget_reset_schedule(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::delete_budget_reset_schedule::Args,
        _authorized: schema::procedures::delete_budget_reset_schedule::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::delete_budget_reset_schedule::Output,
            CratestackError,
        >,
    > + Send {
        let reset_scheduler = self.reset_scheduler.clone();
        let subject = subject_from_ctx(ctx);
        let id = args.args.id;
        async move {
            let _subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;
            reset_scheduler
                .schedules()
                .delete(&id)
                .await
                .map_err(budget_error_to_cratestack_error)?;
            Ok(schema::procedures::delete_budget_reset_schedule::Output { id, deleted: true })
        }
    }

    /// Fires the schedule's pending window immediately, or (with `dryRun`) computes the plan and
    /// writes nothing at all. Same code path either way -- see `ResetScheduler::run_now`. Gated at
    /// `budget:schedule-manage` even for a dry run: the preview enumerates the estate's accounts
    /// and their balances.
    fn run_budget_reset_schedule_now(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::run_budget_reset_schedule_now::Args,
        _authorized: schema::procedures::run_budget_reset_schedule_now::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::run_budget_reset_schedule_now::Output,
            CratestackError,
        >,
    > + Send {
        let reset_scheduler = self.reset_scheduler.clone();
        let subject = subject_from_ctx(ctx);
        let input = args.args;
        async move {
            let _subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            let schedule = reset_scheduler
                .schedules()
                .get(&input.id)
                .await
                .map_err(budget_error_to_cratestack_error)?;
            let window_start = schedule.next_run_at;

            let outcome = reset_scheduler
                .run_now(&input.id, chrono::Utc::now(), input.dryRun)
                .await
                .map_err(budget_error_to_cratestack_error)?;

            Ok(to_schema_reset_schedule_run_result(
                input.id,
                input.dryRun,
                window_start,
                outcome,
            ))
        }
    }

    /// The winning schedule for one budget account and when it next fires. Gated at `budget:read`,
    /// NOT `budget:schedule-manage` -- see the schema doc comment on this procedure.
    fn get_effective_reset_schedule(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::get_effective_reset_schedule::Args,
        _authorized: schema::procedures::get_effective_reset_schedule::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::get_effective_reset_schedule::Output,
            CratestackError,
        >,
    > + Send {
        let reset_scheduler = self.reset_scheduler.clone();
        let subject = subject_from_ctx(ctx);
        let budget_account_id = args.args.budgetAccountId;
        async move {
            let _subject = subject
                .ok_or_else(|| CratestackError::Unauthorized("missing subject".to_owned()))?;

            let effective = reset_scheduler
                .effective_schedule(&budget_account_id)
                .await
                .map_err(budget_error_to_cratestack_error)?;

            Ok(match effective {
                Some(effective) => schema::procedures::get_effective_reset_schedule::Output {
                    nextRunAt: Some(effective.next_run_at),
                    schedule: Some(to_schema_budget_reset_schedule(effective.schedule)),
                },
                None => schema::procedures::get_effective_reset_schedule::Output {
                    schedule: None,
                    nextRunAt: None,
                },
            })
        }
    }

    /// Admin identity resolution (#647). All three bodies live in
    /// [`crate::identity_directory`] -- see that module's doc comment for the authorization story
    /// (the `@allow` clause is the whole of it: no ownership filter, by design) and for why an
    /// unknown id is absent from the result rather than a fabricated placeholder.
    /// Sessions (#649). Both bodies live in [`crate::session_directory`] -- see that module's doc
    /// comment for the asymmetric authorization story (the read is scoped by the `Session` model's
    /// own `@@allow`; the revoke's own-vs-other check has to be in the handler).
    fn query_sessions(
        &self,
        db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::query_sessions::Args,
        _authorized: schema::procedures::query_sessions::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::query_sessions::Output, CratestackError>,
    > + Send {
        let issuer = self.issuer.clone();
        async move { session_directory::query_sessions(db, &issuer.repo, ctx, args.args).await }
    }

    fn revoke_session(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::revoke_session::Args,
        _authorized: schema::procedures::revoke_session::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::revoke_session::Output, CratestackError>,
    > + Send {
        let issuer = self.issuer.clone();
        async move { session_directory::revoke_session(&issuer.repo, ctx, args.args).await }
    }

    fn resolve_user_profiles(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::resolve_user_profiles::Args,
        _authorized: schema::procedures::resolve_user_profiles::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::resolve_user_profiles::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let ctx = ctx.clone();
        async move {
            identity_directory::resolve_user_profiles(&issuer.repo, &ctx, args.args.userIds).await
        }
    }

    /// Unlike its two `user:read` siblings, this one DOES use `db`: its `apiKeyIds` kind is
    /// row-scoped through the generated `db.api_key()` delegate rather than by a permission, the
    /// same `listMyExpiringApiKeys` idiom and for the same reason (the model's own compiled
    /// `@@allow("read", ...)` clause, not a second hand-written ownership join). See
    /// `actor_api_key_labels.rs`.
    fn resolve_actor_labels(
        &self,
        db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::resolve_actor_labels::Args,
        _authorized: schema::procedures::resolve_actor_labels::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::resolve_actor_labels::Output,
            CratestackError,
        >,
    > + Send {
        // `db`/`ctx` are BORROWED into the future rather than cloned, exactly as
        // `list_my_expiring_api_keys` above does -- the only other procedure in this impl that
        // reaches the generated delegate.
        let issuer = self.issuer.clone();
        async move { identity_directory::resolve_actor_labels(db, &issuer.repo, ctx, args.args).await }
    }

    fn search_users(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::search_users::Args,
        _authorized: schema::procedures::search_users::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::search_users::Output, CratestackError>,
    > + Send {
        let issuer = self.issuer.clone();
        let ctx = ctx.clone();
        async move { identity_directory::search_users(&issuer.repo, &ctx, args.args).await }
    }

    /// Platform role grants (ADR-0033). The three `rbac:manage` bodies live in
    /// [`crate::platform_roles_directory`] and `getMyAccess`'s in [`crate::my_access`] -- see
    /// those modules for the authorization story, the revocation session fan-out, and why
    /// `getMyAccess` reads its answer back out of the auth context instead of re-deriving it.
    fn list_platform_role_grants(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::list_platform_role_grants::Args,
        _authorized: schema::procedures::list_platform_role_grants::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::list_platform_role_grants::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let ctx = ctx.clone();
        async move {
            platform_roles_directory::list_platform_role_grants(&issuer.repo, &ctx, args.args).await
        }
    }

    fn grant_platform_role(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::grant_platform_role::Args,
        _authorized: schema::procedures::grant_platform_role::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::grant_platform_role::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let rbac_roles = self.rbac_roles.clone();
        let ctx = ctx.clone();
        async move {
            platform_roles_directory::grant_platform_role(
                &issuer.repo,
                &ctx,
                &rbac_roles,
                args.args,
            )
            .await
        }
    }

    fn revoke_platform_role(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        args: schema::procedures::revoke_platform_role::Args,
        _authorized: schema::procedures::revoke_platform_role::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<
            schema::procedures::revoke_platform_role::Output,
            CratestackError,
        >,
    > + Send {
        let issuer = self.issuer.clone();
        let ctx = ctx.clone();
        async move { platform_roles_directory::revoke_platform_role(&issuer, &ctx, args.args).await }
    }

    fn get_my_access(
        &self,
        _db: &schema::Cratestack,
        ctx: &CratestackContext,
        _args: schema::procedures::get_my_access::Args,
        _authorized: schema::procedures::get_my_access::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::get_my_access::Output, CratestackError>,
    > + Send {
        let issuer = self.issuer.clone();
        let ctx = ctx.clone();
        async move { my_access::get_my_access(&issuer.repo, &ctx).await }
    }

    /// `getBuildInfo` (#573): the build stamp of the service that answered.
    ///
    /// Reads the exact same `lightbridge_authz_core::build_info` value `GET /version` serves, so
    /// the authenticated RPC answer and the unauthenticated HTTP answer can never disagree about
    /// what is running. Touches neither the database nor the caller's identity -- `_db` and `ctx`
    /// are both unused on purpose; the only per-call input is which router mounted this registry.
    fn get_build_info(
        &self,
        _db: &schema::Cratestack,
        _ctx: &CratestackContext,
        _args: schema::procedures::get_build_info::Args,
        _authorized: schema::procedures::get_build_info::Authorized,
    ) -> impl core::future::Future<
        Output = std::result::Result<schema::procedures::get_build_info::Output, CratestackError>,
    > + Send {
        let info = lightbridge_authz_core::build_info(self.service);
        async move {
            Ok(schema::ServerBuildInfo {
                service: info.service,
                version: info.version,
                gitSha: info.git_sha,
                gitShortSha: info.git_short_sha,
                gitCommitDate: info.git_commit_date,
                gitDirty: info.git_dirty,
                rustcVersion: info.rustc_version,
                buildTime: info.build_time,
                imageBuildSha: info.image_build_sha,
                imageTag: info.image_tag,
                imageBuildTime: info.image_build_time,
            })
        }
    }
}
