//! ADR-0021 (`docs/adr/0021-browser-sso-hosted-login-page-and-session-cookie.md`) Decisions 1 +
//! 10, amended by ADR-0029: serves the hosted-login Vite React static build (built in
//! `converse-frontends` as `apps/authz-ui`, consumed here as a digest-pinned OCI artifact, with
//! Vite `base: "/ui/"`) under `authz-idp`'s `/ui` path prefix, with Decision 10's content-hash-aware
//! caching and strict CSP.
//!
//! **Scaffold only (#442).** This module makes the built assets reachable; it does not implement
//! any part of the login flow itself -- the RP leg to Keycloak (#424), `GET /authorize` (#425),
//! or session/cookie issuance (#441, #443) all land as separate, later changes. Nothing in this
//! module reads or writes a cookie, calls Keycloak, or knows what a session is.
//!
//! **Path-scoping is the whole safety property, not mount order.** [`static_assets_fallback`] is
//! mounted via `.nest_service("/ui", ..)` on `build_idp_router`'s router (see that function's doc
//! comment), not as a root-level `.fallback_service(..)`. Nesting under `/ui` means this service
//! only ever receives a request whose original path already started with `/ui` -- it cannot be
//! reached by, and cannot shadow, any protocol route (`.well-known/*`, `/oauth2/*`, `/authorize`,
//! the probe router, all of which live outside `/ui`), regardless of merge order.
//!
//! **Since lightbridge-authz#598, `/ui` is a route ALLOWLIST, not a catch-all.** The whole-subtree
//! SPA fallback ("any path under `/ui` that doesn't match a real file gets `index.html`") is gone.
//! [`load_route_manifest`] reads `dist/routes.json` -- the artifact's own emitted route table
//! (ADR-0029's extended bundle contract, generated by `apps/authz-ui`'s Vite build from its
//! react-router route table, never hand-listed) -- and only THOSE paths get their own explicit
//! `route_service` registration to `index.html`.
//!
//! **A manifest route never shadows a real file -- this is an explicit filesystem check in the
//! registration loop, not an accident of mount/route ordering.** `route_service` registrations
//! always win over the `ServeDir` fallback on a literal path collision regardless of which was
//! registered first, so relying on ordering would be wrong the moment a manifest ever named a path
//! that also happened to be a real file (verified: pre-fix, a manifest route `/sw.js` served
//! `index.html` instead of the real service worker). [`static_assets_fallback`] checks each
//! manifest entry against `static_dir` before registering it and drops (with a `tracing::warn!`
//! naming the route) any entry that already names a real file on disk --
//! `manifest_route_never_shadows_a_real_file` is the regression test. A real file -- under
//! `assets/` or anywhere else in the build output -- always serves via `ServeDir`; everything that
//! is neither a (non-shadowing) manifest route nor a real file is a plain `404`. Manifest missing
//! or unparseable degrades fail-closed to `{"/"}` -- never a panic, never falling back open to the
//! old catch-all -- see [`load_route_manifest`]'s own doc comment for the full reasoning (D11).
//!
//! **This supersedes #462's `RESERVED_PROTOCOL_ROOTS` denylist, which is removed here.** That
//! list existed only because this service was mounted at the router root, where an unknown
//! protocol path could otherwise fall through and render as a successful SPA page; it had to be
//! kept in step by hand every time a new protocol route was accepted. Nesting removes the
//! condition it defended against: a protocol path never reaches this service at all. Keeping it
//! would also be actively wrong here -- `nest_service` strips the `/ui` prefix, so a legitimate
//! client-side route such as `/ui/authorize` would arrive as `/authorize` and be refused. A
//! structural guarantee replaces an enumerated one; there is no dormant second mechanism.

use std::path::Path;

use axum::Router;
use axum::extract::Request;
use axum::http::{HeaderValue, header};
use axum::middleware::{self, Next};
use axum::response::Response;
use tower_http::services::{ServeDir, ServeFile};

/// Vite's default production output directory for content-hashed JS/CSS
/// (`assets/index-<hash>.js`). Anything under this prefix is safe to cache forever: a content
/// change is a different URL, never a cache-invalidation problem (Decision 10).
const HASHED_ASSET_PREFIX: &str = "/assets/";

/// Decision 10: hashed JS/CSS assets are cached as far as HTTP allows.
const IMMUTABLE_CACHE_CONTROL: &str = "public, max-age=31536000, immutable";

/// Decision 10: `index.html` (both the real file and every SPA-fallback response, which is the
/// same file served for an unrecognized path) must always revalidate -- it is the one file whose
/// *content* changes without its own URL changing; it is what references the current hashed
/// bundle.
const NO_CACHE_CONTROL: &str = "no-cache";

/// Decision 10's CSP for the hosted login page: same-origin only, unembeddable by any other
/// origin (mirrors #424's device-grant verification page clickjacking posture, raised stakes here
/// since this page also sets an authentication cookie on success), no inline scripts (Vite's
/// production build does not require any -- verified against a real `vite build` output, not
/// dev-mode HMR injection).
///
/// `pub(crate)` so `crate::relying_party` -- whose device-verification/callback 303 redirects
/// (`redirect_to`, lightbridge-authz#598: the RP leg hands off to the SPA now, it no longer
/// renders any HTML of its own) carry the exact same same-origin, unembeddable posture -- can
/// reuse this constant instead of declaring a byte-identical copy of its own.
pub(crate) const CONTENT_SECURITY_POLICY: &str = "default-src 'self'; frame-ancestors 'none'";

/// The route allowlist the artifact ships (`dist/routes.json`, ADR-0029's extended bundle
/// contract; lightbridge-authz#598). Emitted by `apps/authz-ui`'s Vite build FROM its react-router
/// route table, so the SPA's routes and this server's allowlist cannot drift across two repos --
/// the failure this replaces is "the route works in `vite dev` and 404s in production".
#[derive(serde::Deserialize)]
struct RouteManifest {
    /// The manifest schema version -- checked against [`SUPPORTED_MANIFEST_VERSION`] before any
    /// field below is trusted, so a future incompatible schema change on the producing side
    /// degrades fail-closed instead of this server silently misreading a shape it wasn't built
    /// for.
    version: u32,
    /// Cross-check against this module's own mount prefix. A future `base` change in the SPA that
    /// forgets this side is caught at startup instead of as a blank page.
    basename: String,
    routes: Vec<String>,
}

/// The only `RouteManifest.version` this server knows how to read. A mismatch (older or newer)
/// degrades fail-closed to [`load_route_manifest`]'s `{"/"}` fallback, same as a missing or
/// unparseable manifest -- never an attempt to read a schema this code was not written against.
const SUPPORTED_MANIFEST_VERSION: u32 = 1;

/// The mount prefix `build_idp_router` nests this service under. Not used for matching (the nest
/// strips it before a request arrives) -- only to validate the manifest agrees about it.
const UI_MOUNT_PREFIX: &str = "/ui";

/// FAIL CLOSED, NEVER PANIC, NEVER FAIL OPEN. Three properties, each chosen against a specific
/// failure:
///  - never panic: `missing_static_dir_degrades_to_404_without_panicking` is this module's
///    standing posture. An artifact that predates the manifest (any pin older than #598) must
///    degrade, not crash `authz-idp` at boot.
///  - never fail open: reverting to the old `index.html` catch-all would silently un-fix #598
///    for exactly those old pins -- the one case where nobody would look.
///  - keep `/`: `GET /ui/` staying 200 is asserted by `idp_it.py` and by
///    `ui_bare_and_trailing_slash_both_serve_index_html`, and an old bundle's index.html really
///    does still work. Deep links 404 in this state, which is what makes a stale pin diagnosable
///    rather than silent.
///
/// "Everything else 404s" (this module's own top-level doc comment) is a statement about files and
/// manifest routes, not about every possible response code under `/ui`: a request for a real
/// DIRECTORY path (e.g. `/assets` with no trailing slash, if one ever existed on disk) still goes
/// through `ServeDir`, which can answer with its own `307` redirect to the slash-suffixed form
/// before any 404 logic here is reached. Nothing in this module special-cases that; it is `ServeDir`
/// behavior this function's return value has no way to see or change.
fn load_route_manifest(static_dir: &Path) -> Vec<String> {
    let fallback = || vec!["/".to_string()];
    let path = static_dir.join("routes.json");
    let Ok(raw) = std::fs::read_to_string(&path) else {
        tracing::warn!(
            path = %path.display(),
            "no routes.json in the static bundle; /ui serves only \"/\" until the pin is bumped \
             to an artifact carrying one (ADR-0029)"
        );
        return fallback();
    };
    let Ok(manifest) = serde_json::from_str::<RouteManifest>(&raw) else {
        tracing::warn!(path = %path.display(), "routes.json is not a valid route manifest");
        return fallback();
    };
    if manifest.version != SUPPORTED_MANIFEST_VERSION {
        tracing::warn!(
            version = manifest.version,
            expected = SUPPORTED_MANIFEST_VERSION,
            "routes.json version is not one this server knows how to read"
        );
        return fallback();
    }
    if manifest.basename != UI_MOUNT_PREFIX {
        tracing::warn!(
            basename = %manifest.basename,
            expected = UI_MOUNT_PREFIX,
            "routes.json basename disagrees with this server's /ui mount"
        );
        return fallback();
    }
    // The manifest is UNTRUSTED INPUT from a separately-built artifact, and `Router::route_service`
    // PANICS on a matchit-syntax path and on a duplicate registration. The ASCII allowlist below
    // (`chars().all(..)`) is the OPERATIVE guard against the first: axum 0.8/matchit 0.8's
    // metacharacters are `{` and `}` (`{param}`, `{*wildcard}`), both already excluded by that
    // allowlist -- not the axum 0.7-era `:param`/`*wildcard` syntax the `!route.contains(':')`/
    // `!route.contains('*')` checks below still test for. Those two are kept as belt-and-braces
    // against a future matchit downgrade, not the reason a manifest route is safe to register
    // today. `seen` below is the guard against the second (duplicate-registration) panic.
    let mut seen = std::collections::BTreeSet::new();
    let mut routes: Vec<String> = Vec::new();
    for route in manifest.routes {
        let ok = route.starts_with('/')
            && !route.contains(':')
            && !route.contains('*')
            && !route.contains("//")
            && route
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || "/-._~".contains(c))
            // A segment that is only dots (`.`/`..`) is a path-traversal shape `ServeDir` would
            // otherwise have to defend against on its own; reject it here so a manifest can never
            // even attempt to name one.
            && route.split('/').all(|segment| segment != "." && segment != "..");
        if !ok {
            tracing::warn!(%route, "ignoring an unusable route from routes.json");
            continue;
        }
        if seen.insert(route.clone()) {
            routes.push(route);
        } else {
            tracing::warn!(%route, "ignoring a duplicate route from routes.json");
        }
    }
    if routes.is_empty() {
        fallback()
    } else {
        routes
    }
}

/// Builds the static-asset service `build_idp_router` mounts under `/ui` (`.nest_service("/ui",
/// ..)`).
///
/// `static_dir` is the Vite build's `dist/` output (an `index.html`, a content-hashed `assets/`
/// directory, and -- since #598 -- a `routes.json` route manifest, all built with Vite
/// `base: "/ui/"`). This function's own paths (`/`, `/assets/...`) are relative to wherever it is
/// mounted -- `axum::Router::nest_service` strips the `/ui` prefix before a request reaches here,
/// so `GET /ui` and `GET /ui/` both arrive as `/` and `GET /ui/assets/<file>` arrives as
/// `/assets/<file>`, exactly like the caller mounted this router at the origin.
///
/// Each path [`load_route_manifest`] returns gets its own explicit route to `index.html` --
/// UNLESS that path already names a real file on disk, in which case it is skipped (logged via
/// `tracing::warn!`) so the file wins; that skip is an explicit filesystem check below, not an
/// artifact of `route_service` vs. `ServeDir` ordering -- a `route_service` registration always
/// wins a literal path collision over the `fallback_service` below regardless of which was
/// registered first, so relying on ordering to keep a real file reachable would be silently wrong
/// the moment a manifest ever named that file's path (`manifest_route_never_shadows_a_real_file`
/// is the regression test). Every other path either matches a real file (still served via
/// `ServeDir`, since a content-hashed filename under `assets/` is not a route the manifest needs
/// to know about) or is a bare `404`. There is no more `.fallback(ServeFile::new(index))`
/// whole-subtree catch-all -- that is exactly what #598 removes. Every response -- allowlisted
/// route, real asset, or 404 -- carries Decision 10's cache headers and CSP (the 404 gets them
/// too, via the same middleware layer, so it is never distinguishable from an allowlisted response
/// by header shape alone).
pub fn static_assets_fallback(static_dir: impl AsRef<Path>) -> Router {
    let static_dir = static_dir.as_ref();
    let index_html = static_dir.join("index.html");

    let serve_dir = ServeDir::new(static_dir);

    let mut router = Router::new();
    for route in load_route_manifest(static_dir) {
        let real_file = static_dir.join(route.trim_start_matches('/'));
        if real_file.is_file() {
            tracing::warn!(
                %route,
                path = %real_file.display(),
                "ignoring a manifest route that shadows a real static file; the file wins"
            );
            continue;
        }
        router = router.route_service(route.as_str(), ServeFile::new(&index_html));
    }

    router
        .fallback_service(serve_dir)
        .layer(middleware::from_fn(apply_static_asset_headers))
}

/// Decision 10's cache-control + CSP posture, applied uniformly after the file (or SPA-fallback
/// `index.html`) has already been resolved -- this never changes *which* file is served, only the
/// headers on the response.
async fn apply_static_asset_headers(req: Request, next: Next) -> Response {
    let is_hashed_asset = req.uri().path().starts_with(HASHED_ASSET_PREFIX);
    let mut response = next.run(req).await;

    let headers = response.headers_mut();
    headers.insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static(if is_hashed_asset {
            IMMUTABLE_CACHE_CONTROL
        } else {
            NO_CACHE_CONTROL
        }),
    );
    headers.insert(
        header::CONTENT_SECURITY_POLICY,
        HeaderValue::from_static(CONTENT_SECURITY_POLICY),
    );

    response
}
