[package]
name = "lightbridge-authz-api-key"
version = "0.1.0"
edition = "2024"

[dependencies]
lightbridge-authz-core.workspace = true
uuid.workspace = true
anyhow.workspace = true
chrono.workspace = true
serde_json.workspace = true
diesel.workspace = true
diesel-async.workspace = true
argon2.workspace = true
rand_core.workspace = true
