{{- if and .Values.tls.enabled .Values.tls.job.enabled .Values.tls.job.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lightbridge-authz.tlsJobRoleBindingName" . }}
  labels:
    {{- include "lightbridge-authz.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lightbridge-authz.tlsJobRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lightbridge-authz.tlsJobServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
