[package]
name = "lightbridge-authz-bearer"
version = "0.1.0"
edition = "2024"

[dependencies]
lightbridge-authz-core.workspace = true
anyhow.workspace = true
serde.workspace = true
serde.features = ["derive"]
jwks.workspace = true
jsonwebtoken.workspace = true
tracing.workspace = true
